print("Importing...")
from transformers import CLIPProcessor, CLIPModel, CLIPTokenizer
print("Imported.")
print("Loading Model...")
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
print("Model Loaded.")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
print("Processor Loaded.")
tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32")
print("Tokenizer Loaded.")
